// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCcE_bX_PDEhPWtXHCp9QdO73Fgwhe_AI',
    appId: '1:868734694185:web:719e4384350c0ea2d03d38',
    messagingSenderId: '868734694185',
    projectId: 'hack-now-dfc21',
    authDomain: 'hack-now-dfc21.firebaseapp.com',
    storageBucket: 'hack-now-dfc21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERjH2HutnzxVVnMiXBKzcddQ8vyl72fA',
    appId: '1:733043232151:android:1c181f005512d9dd5e48d2',
    messagingSenderId: '733043232151',
    projectId: 'devhouse-25',
    storageBucket: 'devhouse-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgi47h2pO1snIzWa3HpK3kVE9Vs5AkOZo',
    appId: '1:733043232151:ios:480c4129aeedb5415e48d2',
    messagingSenderId: '733043232151',
    projectId: 'devhouse-25',
    storageBucket: 'devhouse-25.firebasestorage.app',
    iosBundleId: 'com.example.hacknow',
  );

}